import { db } from "../../db/database.ts";

// Все statements готовятся один раз на старте: SQLite не парсит SQL внутри
// обработчиков событий.
export const stmt = {
  guildInsert: db.prepare("INSERT OR IGNORE INTO guilds(id,name,icon,updated_at) VALUES(?,?,?,?)"),
  guildName: db.prepare("SELECT name FROM guilds WHERE id=?"),
  guildIds: db.prepare("SELECT id FROM guilds"),
  rules: db.prepare("SELECT kind,enabled,action_json,threshold_json,window_seconds,escalation FROM automod_rules WHERE guild_id=? AND enabled=1"),
  security: db.prepare("SELECT ignored_role_ids_json,protected_channel_id FROM guild_security_settings WHERE guild_id=?"),
  welcomeSettings: db.prepare("SELECT * FROM welcome_settings WHERE guild_id=?"),
  loggingSettings: db.prepare("SELECT channel_id,categories_json FROM logging_settings WHERE guild_id=?"),
  metric: db.prepare("INSERT INTO guild_daily_metrics(guild_id,day,joins,leaves,messages,moderation,active_users,peak_messages) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(guild_id,day) DO UPDATE SET joins=joins+excluded.joins,leaves=leaves+excluded.leaves,messages=messages+excluded.messages,moderation=moderation+excluded.moderation,active_users=active_users+excluded.active_users,peak_messages=MAX(peak_messages,excluded.peak_messages)"),
  channelMetric: db.prepare("INSERT INTO guild_daily_channel_stats(guild_id,day,channel_id,messages) VALUES(?,?,?,?) ON CONFLICT(guild_id,day,channel_id) DO UPDATE SET messages=messages+excluded.messages"),
  userMetric: db.prepare("INSERT INTO guild_daily_user_stats(guild_id,day,user_id,messages) VALUES(?,?,?,?) ON CONFLICT(guild_id,day,user_id) DO UPDATE SET messages=messages+excluded.messages"),
  hourlyMetric: db.prepare("INSERT INTO guild_hourly_messages(guild_id,day,hour,messages) VALUES(?,?,?,?) ON CONFLICT(guild_id,day,hour) DO UPDATE SET messages=messages+excluded.messages"),
  cleanupChannelStats: db.prepare("DELETE FROM guild_daily_channel_stats WHERE day<?"),
  cleanupUserStats: db.prepare("DELETE FROM guild_daily_user_stats WHERE day<?"),
  cleanupHourlyStats: db.prepare("DELETE FROM guild_hourly_messages WHERE day<?"),
  cleanupDailyStats: db.prepare("DELETE FROM guild_daily_metrics WHERE day<?"),
  tempPresets: db.prepare("SELECT * FROM temp_channel_presets WHERE guild_id=? ORDER BY id"),
  tempAll: db.prepare("SELECT * FROM temp_channels"),
  tempByOwner: db.prepare("SELECT * FROM temp_channels WHERE guild_id=? AND owner_id=?"),
  tempByChannel: db.prepare("SELECT * FROM temp_channels WHERE channel_id=?"),
  tempInsert: db.prepare("INSERT INTO temp_channels(guild_id,channel_id,owner_id,panel_message_id,source_channel_id,created_at) VALUES(?,?,?,?,?,?)"),
  tempDelete: db.prepare("DELETE FROM temp_channels WHERE channel_id=?"),
  tempDeleteByGuild: db.prepare("DELETE FROM temp_channels WHERE guild_id=?"),
  tempUpdateOwner: db.prepare("UPDATE temp_channels SET owner_id=? WHERE channel_id=?"),
  tempUpdatePanel: db.prepare("UPDATE temp_channels SET panel_message_id=? WHERE channel_id=?"),
  panel: db.prepare("SELECT role_limit,role_mode,notify_enabled,notify_template FROM self_role_panels WHERE id=? AND guild_id=?"),
  panelOptionIds: db.prepare("SELECT role_id FROM self_role_options WHERE panel_id=?"),
  panelOptionEmoji: db.prepare("SELECT role_id,emoji FROM self_role_options WHERE panel_id=?"),
  automodRecent: db.prepare("SELECT COUNT(*) AS count FROM moderation_actions WHERE guild_id=? AND user_id=? AND type='automod' AND created_at>?"),
  panelDelete: db.prepare("DELETE FROM self_role_panels WHERE guild_id=? AND channel_id=? AND message_id=?"),
  embedDetach: db.prepare("UPDATE embeds SET channel_id=NULL,message_id=NULL,updated_at=? WHERE guild_id=? AND channel_id=? AND message_id=?"),
  warns: db.prepare("SELECT m.reason,m.created_at FROM moderation_actions m WHERE m.guild_id=? AND m.user_id=? AND m.type='warn' AND NOT EXISTS(SELECT 1 FROM appeals a WHERE a.punishment_id=m.id AND a.status='approved') ORDER BY m.created_at DESC"),
  moderationInsert: db.prepare("INSERT INTO moderation_actions(guild_id,user_id,moderator_id,type,reason,created_at) VALUES(?,?,?,?,?,?)"),
  warnIds: db.prepare("SELECT id FROM moderation_actions WHERE guild_id=? AND type='warn' AND (? IS NULL OR user_id=?)"),
  warnDelete: db.prepare("DELETE FROM moderation_actions WHERE guild_id=? AND type='warn' AND (? IS NULL OR user_id=?)"),
  appealDeleteByPunishment: db.prepare("DELETE FROM appeals WHERE punishment_id=?"),
  dataVersion: db.prepare("PRAGMA data_version"),
  panelReactions: db.prepare("SELECT id,role_mode,message_id FROM self_role_panels WHERE guild_id=? AND style='reaction'"),
  messageUpsert: db.prepare("INSERT INTO message_cache(message_id,guild_id,channel_id,content,created_at) VALUES(?,?,?,?,?) ON CONFLICT(message_id) DO UPDATE SET content=excluded.content"),
  messageGet: db.prepare("SELECT content FROM message_cache WHERE message_id=?"),
  messageDelete: db.prepare("DELETE FROM message_cache WHERE message_id=?"),
  messagePrune: db.prepare("DELETE FROM message_cache WHERE guild_id=? AND created_at < (SELECT created_at FROM message_cache WHERE guild_id=? ORDER BY created_at DESC LIMIT 1 OFFSET ?)"),
  musicSettings: db.prepare("SELECT * FROM music_settings WHERE guild_id=?"),
  musicSessionUpsert: db.prepare("INSERT INTO music_sessions(guild_id,channel_id,message_id,updated_at) VALUES(?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET channel_id=excluded.channel_id,message_id=excluded.message_id,updated_at=excluded.updated_at"),
  musicSessionDelete: db.prepare("DELETE FROM music_sessions WHERE guild_id=?"),
  musicSessionAll: db.prepare("SELECT guild_id,channel_id,message_id FROM music_sessions"),
};
